### ISSUE TITLE
Direct GGUF: `ImportError: cannot import name 'GGML_TYPE_F16' from 'llama_cpp'` on `llama-cpp-python` >= 0.3.35

### ISSUE THREAD

**Issue by fullthrottler** [duckyshell/ComfyUI-MiniMaxH3-Prompt-Writer#7]
#### 1. Runtime Compatibility Probe Fails on `llama-cpp-python` >= 0.3.35
When opening **Settings -> Direct GGUF**, the following runtime warning appears even though a compatible CUDA wheel of `llama-cpp-python` is properly installed:

> **Runtime**
> llama-cpp-python is installed, but the runtime is not usable.
> The native compatibility check did not find a working GPU runtime. Version 0.3.35 was detected.

#### Cause

In `llama-cpp-python` **0.3.35+**, `GGML_TYPE_F16` and `GGML_TYPE_Q8_0` are no longer directly exported from top-level `llama_cpp`. Instead, they reside in `llama_cpp._ggml.GGMLType`.
As a result, `_CHILD_PROBE` in `backend/runtime_diagnostics.py` and `load()` in `backend/models/gguf_backend.py` throw:
`ImportError: cannot import name 'GGML_TYPE_F16' from 'llama_cpp'`

#### Proposed Fix

Add a fallback to import from `llama_cpp._ggml`:
```python
from llama_cpp import Llama, LogitsProcessorList
try:
    from llama_cpp import GGML_TYPE_F16, GGML_TYPE_Q8_0
except ImportError:
    import llama_cpp._ggml as ggml
    GGML_TYPE_F16 = ggml.GGMLType.GGML_TYPE_F16.value
    GGML_TYPE_Q8_0 = ggml.GGMLType.GGML_TYPE_Q8_0.value
```

### Environment
- **OS:** Windows 11
- **Python / ComfyUI:** ComfyUI Windows Portable (Python 3.12 / 3.13)
- **GPU:** NVIDIA GeForce RTX (CUDA 13.0)
- **llama-cpp-python:** `0.3.35`
- **ComfyUI-MiniMaxH3-Prompt-Writer:** `0.3.2`
- **Gemini 3.7 Flash**

**Comment by duckyshell** [comment]
fixed on main. 

Direct GGUF now supports both the older top-level GGML_TYPE_* exports and the newer llama_cpp._ggml.GGMLType layout.

could you update and confirm whether it works with your llama-cpp-python 0.3.35 setup?

**Comment by fullthrottler** [comment]
Thank you for the rapid update!

Although llama-cpp-python is now being loaded, it appears the logic is currently hard-coded to recognize only gemma4 as a Vision model, so I haven't been able to verify that it works on my local Qwen models. I will open a separate issue regarding this.
